
version: '3.8'

services:
  # Development Environment
  dev:
    container_name: chronotask_dev
    image: node:20-alpine
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
      - chronotask_data_dev:/app/.data
    ports:
      - "9004:9004"
    environment:
      NODE_ENV: development
      JWT_SECRET: "your_dev_jwt_secret_here_change_me"
      NEXT_PUBLIC_BYPASS_AUTH: "true"

  # Production Environment
  prod:
    container_name: chronotask_prod
    # Replace YOUR_GITHUB_USERNAME with your actual GitHub username or organization name
    image: ghcr.io/chimpsec/chronotask:latest
    restart: unless-stopped
    ports:
      - "3005:3000"
    volumes:
      - chronotask_data_prod:/app/.data # Persist SQLite DB for prod
    environment:
      NODE_ENV: production
      PORT: 3000
      JWT_SECRET:
    env_file:
      - .env

volumes:
  chronotask_data_dev:
  chronotask_data_prod:

networks:
  t3_proxy:
    external: true
      