## Traefik Middleware Configuration for ChronoChimp
## This file defines middleware components to be used with your Traefik setup

http:
  middlewares:
    # Security Headers - Apply basic security headers to all requests
    secure-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        contentSecurityPolicy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self'"
        referrerPolicy: "strict-origin-when-cross-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    
    # Compression middleware - Compresses responses to improve performance
    compress:
      compress: {}
    
    # HTTPS Redirect - Ensures all traffic uses HTTPS
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
    
    # CORS Headers - Configured to match your CORS settings
    cors-headers:
      headers:
        accessControlAllowMethods: "GET,POST,PUT,DELETE,OPTIONS"
        accessControlAllowOriginList: "https://chronochimp.example.com"
        accessControlMaxAge: 100
        addVaryHeader: true
    
    # Forward authentication headers properly
    auth-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Host: "chronochimp.example.com"  # Update with your domain
    
    # Rate limiting to prevent abuse
    rate-limit:
      rateLimit:
        average: 100
        burst: 50
    
    # Chain middlewares together for common use cases
    chronochimp-secured:
      chain:
        middlewares:
          - secure-headers
          - compress
          - auth-headers
    
    chronochimp-api:
      chain:
        middlewares:
          - secure-headers
          - compress
          - cors-headers
          - auth-headers
          - rate-limit

# Example router configuration (for reference)
# Include this in your Traefik dynamic configuration
#
# http:
#   routers:
#     chronochimp:
#       rule: "Host(`chronochimp.example.com`)"
#       service: "chronochimp"
#       entryPoints:
#         - "websecure"
#       middlewares:
#         - "chronochimp-secured"
#       tls: {}
#
#     chronochimp-api:
#       rule: "Host(`chronochimp.example.com`) && PathPrefix(`/api`)"
#       service: "chronochimp"
#       entryPoints:
#         - "websecure"
#       middlewares:
#         - "chronochimp-api"
#       tls: {}
