## Traefik Static Configuration
## Place this file at traefik/traefik.yml

# Global configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Enable API and dashboard
api:
  dashboard: true
  insecure: false

# EntryPoints configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

# Configure providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: web
  
  file:
    directory: "/config"
    watch: true

# Configure certificate resolver
certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@chronochimp.example.com  # Change to your email
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web

# Access logs
accessLog:
  filePath: "/data/access.log"
  format: json

# Log settings
log:
  level: INFO
