
name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main # Or your default branch, e.g., master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/chronochimp # Replace 'chronochimp' if your app name is different

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Optional: Build arguments like JWT_SECRET can be passed here if needed
          # build-args: |
          #   JWT_SECRET_ARG=${{ secrets.JWT_SECRET_PROD }}
          # However, it's generally better to pass secrets as runtime environment variables
          # to the container, not build-time args unless absolutely necessary for the build process.
